# Generated by Django 3.0.6 on 2020-06-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_group',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='user_group',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
