# Generated by Django 3.0.6 on 2020-06-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_auto_20200616_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True)),
                ('QuestionGroup', models.ManyToManyField(blank=True, to='polling.QuestionGroup')),
            ],
        ),
    ]
