# Generated by Django 3.0.6 on 2020-06-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invitation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polling.Invitation')),
            ],
        ),
    ]
