# Generated by Django 3.0.6 on 2020-06-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0005_auto_20200616_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='QuestionGroup',
        ),
        migrations.AddField(
            model_name='invitation',
            name='QuestionGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polling.QuestionGroup'),
        ),
    ]
