# Generated by Django 3.0.6 on 2020-06-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('polling', '0007_auto_20200618_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='user_group',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
