# Generated by Django 3.0.6 on 2020-06-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('polling', '0008_invitation_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
