# Generated by Django 3.0.6 on 2020-06-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0009_auto_20200618_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='email',
        ),
    ]
